#!/bin/bash

command=$1
username=$2
userID=$3

file=$HOME/.local/share/subashtion/subscriptions.txt
newestVid=$(curl -s "https://vid.puffyan.us/channel/$userID" | grep dir | awk '{if(NR==2) print substr($0, 31, length($0)-34)}')

check()
{
  userID=$(awk -v pattern=", $username$" '{if($0~pattern) x=NR+1} (NR==x){print substr($0, 3)}' $file)
  newestVid=$(curl -s "https://vid.puffyan.us/channel/$userID" | grep dir | awk '{if(NR==2) print substr($0, 31, length($0)-34)}')
  prevVid=$(awk -v pattern=", $username$" '{if($0~pattern) x=NR+2} (NR==x){print substr($0, 3)}' $file)
  if [[ $prevVid != $newestVid && $newestVid != "" ]]; then
    notify-send "$username" "$newestVid"
    newfile=$(awk -v pattern="^, $username" -v newVid="- $newestVid" '{if($0 ~ pattern)x=NR+2;}{if(NR!=x)print; else print (newVid)}' $file)
    echo "$newfile" > $file
  fi
}

print_help()
{
   # Display Help
   echo "Syntax: sb [command] [arguments]"
   echo 
   echo "commands:"
   echo "add [username] [userID]  Subscribe to a youtube account"
   echo "remove [username]        Unsubscribe a youtube account"
   echo "check [username]         Check if youtube account uploaded a new video"
   echo "list                     List all subscriptions"  
   echo "help                     Print this help message"  
   echo 
   echo "You can use sb with no command to run check on all youtube accounts you subscribed to."
}

if [[ $command == "add" && $(grep ", $username" $file | wc -l) == 0 && $newestVid != "" ]]; then
  echo -e ", $username\n. $userID\n- $newestVid" >> $file
  echo "Latest video: $newestVid"
elif [[ $command == "check" && $(grep "^, $username" $file | wc -l) != 0 ]]; then
  check &
  if [[ $new_vid_found != "yes" ]]; then
    notify-send "No new video was uploaded"
  fi
elif [[ $command == "remove" && $(grep "^, $username" $file | wc -l) != 0 ]]; then
  newfile=$(awk -v pattern="^, $username" '{if($0 ~ pattern)x=NR+2;}!(NR<=x){print}' $file)
  if [[ $newfile ]]; then
    echo "$newfile" > $file
  fi
elif [[ $command == "list" ]]; then
  while read -r line
  do
    username=$(echo "$line" | awk '/^,/{print substr($0, 3)}')
    if [[ $username ]]; then
      vid=$(awk -v pattern=", $username$" '{if($0~pattern) x=NR+2} (NR==x){print substr($0, 3)}' $file)
      printf '%-15s: %s\n' "$username" "$vid"
    fi
  done < $file
elif [[ $command == "help" ]]; then
  print_help
else
  while read -r line
  do
    username=$(echo "$line" | awk '/^,/{print substr($0, 3)}')
    if [[ $username ]]; then
      check &
    fi
  done < $file
fi
